[metadata]
template_description = """\
    Generate a new Poetry project with a basic directory structure and \
    tooling.\
    """
template_requirements = ["poetry", "pyyaml"]
templating_excludes = ["**/.venv/**"]